import { useState, useEffect } from 'react';
import { useFetch } from '../hooks/useFetch';
import type { NextPage } from 'next';
import styles from '../styles/Home.module.css';

import Head from 'next/head';
import SearchBar from '../components/SearchBar';
import PokemonsContainer from '../components/PokemonsContainer';

const Home: NextPage = () => {
  // const [endpoint, setEndpoint] = useState<string>('pokemon');
  const [targetSearchedPokemon, setTargetSearchedPokemon] = useState('');
  const { data, loading, error } = useFetch(`pokemon?limit=151` /*endpoint*/);
  const { results } = data || [];

  console.log('Results? :>', results);

  const findPokemon = (pokemon: string): void => {
    const [targetPokemon] = results.filter((p) => p.name === pokemon);
    const { url } = targetPokemon || {};
    setTargetSearchedPokemon(url ? url : '');
  };

  if (loading) return <h1>Loading</h1>;
  if (error) return <h2>Error</h2>;

  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon!</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Pokemon finder</h1>

        <p className={styles.description}>
          El que quiere Pokemons, que los busque!
        </p>

        <SearchBar findPokemon={findPokemon} />

        <PokemonsContainer
          targetSearchedPokemon={targetSearchedPokemon}
          results={results}
        />
      </main>
    </div>
  );
};

export default Home;
